uicc0 = {
  imsi = "2089900007487";
  key = "fec86ba6eb707ed08905757b1bb44b8f";
  opc  = "C42449363BBAD02B66D16BC975D77CC1";
  dnn  = "oai";
  nssai_sst = 1;
  nssai_sd  = 1;
}

uecapability = {
  ue_nr_capability = "uecapability_nr.xml";
}

nr_rrc = {
  enable_RRC_connection_establishment = 1;
}

nr_signaling_preconfiguration = {
  preconfigured = 1;
}

position0 = {
  x = 0.0;
  y = 0.0;
  z = 6377900.0;
}

//@include "channelmod_rfsimu_LEO_satellite.conf"

/* ===========================
 * RFsim: UE 作為 client
 * 連到本機 gNB 的 4043
 * =========================== */
rfsimulator = {
  serveraddr = "127.0.0.1";
  serverport = 4043;
  options = ();
};

